name: MMB_SWOT_2024
channels:
  - conda-forge
dependencies:
  - contextily
  - dask
  - earthaccess
  - geopandas
  - h5py
  - ipykernel
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pyarrow
  - xarray
  - psycopg2-binary
  - geoalchemy2
  - sqlalchemy
  - beautifulsoup4
