name: SWOT_2024_ANC2
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - contextily
  - netcdf4
  - h5py
  - xarray
  - earthaccess
  - ipykernel
  - jupyter